# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Joked' do
  use_frameworks!
  pod "Koloda"
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
end
